### ISSUE TITLE
which consumer do you recommend for production?

### ISSUE THREAD

**Issue by pablocastilla** [kashifsoofi/aws#4]
Hi Kashif!

We are starting to use kinesis and we see that in dotnet we have two options, the plain library or the one with the java daemon.

Do you think using the first option, which is easier at deployment level, is feasible or too complex? 

Thanks

**Comment by kashifsoofi** [comment]
Implementing with plan library is definitely easier as if you are a dotnet developer you can look at everything. however if i remember correctly dotnet library does not provide notifications of incoming events (you would have to implement polling) and you have to manually keep track of the records that you have processed if you are not deleting those. With Daemon it keeps track of the processed messages with dynamo i think and also encapsulates the polling nicely.
